# DMM

## **Overview** 
Tests if the DMM is working properly by initializing, closing, and reading DC Voltage/Current at given UUT Pins.

## **DMMInitialize**

### Header 
`int DLLEXPORT __stdcall DMMInitialize(char *resource_name, ViSession *dmm_handle, ViBoolean *test_result, char *status_message)`

### Purpose 
Initializes the digital multimeter.

### Parameters
| Parameter | Type | Description |
|------|------|-----|
|`resource_name`|`char *`|Resource name|
|`dmm_handle`|`ViSession *`|Address of dmm session|
|`test_result`|`ViBoolean *`|Either VI_TRUE or VI_FALSE|
|`status_message`|`char *`|String error message|

### Return Values
|Error Code| Description|
|----------|-----------------|
|`VI_SUCCESS`|NiDMM initialized successfully|
|`Other`|Error when calling InitWithOptions() or ConfigurePowerLineFrequency() 

## **DMMClose**

### Header 
`int DLLEXPORT __stdcall DMMClose(ViSession dmm_handle, char *status_message)`

### Purpose 
Closes digital multimeter.

### Parameters
| Parameter | Type | Description |
|------|------|-----|
|`dmm_handle`|`ViSession`|Address of dmm device|
|`status_message`|`char *`|String error message|

### Return Values
|Error Code| Description|
|----------|-----------------|
|`VI_SUCCESS`|DMM closed successfully|
|`Other`|DMM failed to close|


## **DMMMeasure**

### Header 
`int DLLEXPORT __stdcall DMMMeasure(ViSession dmm_handle, MeasurementType measurement_type, ViReal64 range, ViReal64 *reading, char *status_message)`

### Purpose
Reads the DC Voltage at the given UUT pins with DMM and stores read value in Reading.

### Parameters
| Parameter | Type | Description |
|------|------|-----|
|`dmm_handle`|`ViSession`|Address of dmm device|
|`measurement_type`|`MeasurementType`|Enum that specifies measurement type|
|`range`|`ViReal64`|Specifies minimum measurement val (frequency) or max measurement val (all other functions)|
|`reading`|`ViReal64 *`|Measurement reading of dmm|
|`status_message`|`char *`|String error message|

### Return Values
|Error Code| Description|
|----------|-----------------|
|`VI_SUCCESS`|DMM was measured successfully|
|`Other`|DMM failed to measure|