# Photometer 

## Overview
Test display unit using photometer

## PhotometerMeasure

### Header

```         
int DLLEXPORT __stdcall PhotometerMeasure(unsigned int com_port, double *luminance, double *chromaticity_x, double *chromaticity_y, double *u_prime, double *v_prime);
```

### Purpose

Measures luminance, chromaticity x&y, u/v prime using photometer functions.

### Parameters

| Parameter        | Type         | Description                         |
|------------------|--------------|---------------------------------|
| `com_part`       | `unsigned int` | Port to measure from            |
| `luminance`      | `double \*`    | Luminance value (Lv)            |
| `chromaticity_x` | `double \*`    | Chromaticity x coordinate       |
| `chromaticity_y` | `double \*`    | Chromaticity y coordinate       |
| `u_prime`        | `double \*`    | Scaled factor of chromaticity_x |
| `v_prime`        | `double \*`    | Scaled factor of chromaticity_y |

### Return Value

| Error Code | Description |
|------------|---------|
| `0`        | Success |
| `Other`      | Error   |

## PhotometerInitialize

### Header

```         
int DLLEXPORT __stdcall PhotometerInitialize(unsigned int com_port, ViBoolean *test_result, char *status_message);
```

### Purpose

Initialize photometer with parameter values

### Parameters

| Parameter        | Type         | Description            |
|------------------|--------------|--------------------|
| `com_part`       | `unsigned int` | Communication port |
| `test_result`    | `ViBoolean \*` | Test result        |
| `status_message` | `char \*`      | Status message     |

### Return Value

| Error Code | Description   |
|------------|---------|
| `0`        | Success |
